version: '3.8'

services:
  dbt:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    image: northwind/dbt:postgres
    container_name: northwind-container
    volumes:
      - .:/app
    env_file:
      - .dbt_env
    environment:
      DBT_PROFILES_DIR: C:/Users/User/.dbt
    working_dir: C:/Users/User/project_2/northwind_project
    command: tail -f /dev/null
