
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'northwind_project'
version: '1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'northwind_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
#data-paths: ["data"]

# Configuring paths for documentation and tests
test-paths: ["tests"]
docs-paths: ["docs"]

# Configuring target paths for manifest and run results
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Defining models configuration
models:
  northwind_project:
    # Default configurations for all models
    materialized: table
    # staging:
    #   +schema: raw_data
    #   +materialized: table
    # warehouse:
    #   +schema: data_warehouse
    #   +materialized: table
    # marts:
    #   +schema: data_mart
    #   +materialized: table

# Defining seeds configuration
seeds:
  northwind_project:
    +schema: seeds

# Defining snapshots configuration
snapshots:
  dbt_dskola_project:
    +schema: snapshots

# Defining sources configuration
# sources:
#   dbt_dskola_project:
#     staging:
#       customers:
#         - +enabled: true
#       orders:
#         - +enabled: true
#       payments:
#         - +enabled: true
#       products:
#         - +enabled: true

# Configuring packages
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.6

# Configuring on-run-start and on-run-end hooks
on-run-start: []
on-run-end: []

# Configuring vars
vars: {}

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
#models:
  #northwind_project:
    # Config indicated by + and applies to all files under models/example/
    #example:
      #+materialized: view
#seeds:
  #northwind_project:
    #+schema: public