version: 2

sources:
  - name: northwind_project
    schema: public
    tables:
      - name: fact_order_details
      - name: fact_orders
      - name: dim_products
      - name: dim_suppliers
      - name: dim_employees
      - name: dim_categories

models:
  - name: stg_fact_order_details
    description: "Staging table for fact_order_details"
    tests:
      - unique:
          - orderID
      - not_null:
          - orderID
          - productID
          - unitPrice
          - quantity
          - discount

  - name: stg_fact_orders
    description: "Staging table for fact_orders"
    tests:
      - unique:
          - orderID
      - not_null:
          - orderID
          - customerID
          - employeeID
          - orderDate
          - requiredDate
          - shippedDate
          - shipVia
          - freight
          - shipName
          - shipAddress
          - shipCity
          - shipRegion
          - shipPostalCode
          - shipCountry

  - name: stg_dim_products
    description: "Staging table for dim_products"
    tests:
      - unique:
          - productID
      - not_null:
          - productID
          - productName
          - supplierID
          - categoryID
          - quantityPerUnit
          - unitPrice
          - unitsInStock
          - unitsOnOrder
          - reorderLevel
          - discontinued

  - name: stg_dim_suppliers
    description: "Staging table for dim_suppliers"
    tests:
      - unique:
          - supplierID
      - not_null:
          - supplierID
          - companyName,
          - contactName,
          - contactTitle,
          - address,
          - city,
          - region,
          - postalCode,
          - country,
          - phone,
          - fax,
          - homePage

  - name: stg_dim_categories
    description: "Staging table for dim_categories"
    tests:
      - unique:
          - categoryID
      - not_null:
          - categoryID
          - categoryName
          - description
          - picture

  - name: stg_dim_employees
    description: "Staging table for dim_employees"
    tests:
      - unique:
          - employeeID
      - not_null:
          - employeeID
          - lastName
          - firstName
          - title
          - titleOfCourtesy
          - birthDate
          - hireDate
          - address
          - city
          - region
          - postalCode
          - country
          - homePhone
          - extension
          - photo
          - notes
          - reportsTo
          - photoPath
          
models:
  - name: dm_monthly_supplier_gross_revenue
    description: "Monthly gross revenue by supplier"
    columns:
      - name: company_name
        description: "Name of the supplier company"
        tests:
          - not_null
      - name: month_order
        description: "Month of the order in YYYY-MM format"
        tests:
          - not_null
      - name: gross_revenue
        description: "Gross revenue generated by the supplier in the given month"
        tests:
          - not_null
models:
  - name: top_category_sales
    description: "Top category product sales by month"
    columns:
      - name: category_name
        description: "Name of the product category"
        tests:
          - not_null
      - name: month_order
        description: "Month of the order in YYYY-MM format"
        tests:
          - not_null
      - name: total_sold
        description: "Total quantity sold in the given month"
        tests:
          - not_null
models:
  - name: top_employee_revenue
    description: "Top employee revenue by month"
    columns:
      - name: employee_name
        description: "Name of the employee"
        tests:
          - not_null
      - name: month
        description: "Month of the order in YYYY-MM format"
        tests:
          - not_null
      - name: gross_revenue
        description: "Gross revenue generated by the employee in the given month"
        tests:
          - not_null


  